### ISSUE TITLE
CICD: Add "build" to docker-compose file

### ISSUE THREAD

**Issue by ProgrammingByPermutation** [nullinside-development-group/nullinside-api#60]
Since we're using docker compose files we should also place the build specification in the docker compose file rather than allowing the `.sh` files to control the build logic. 

Example build section:
```
        build: 
            context: .
            dockerfile: Dockerfile-angular-react
            args:
                BUILD_ENVIRONMENT: ${BUILD_ENVIRONMENT}
                IP_ADDRESS: ${IP_ADDRESS}
```
